package cmd

import (
	"fmt"
	"path/filepath"

	"github.com/spf13/cobra"

	epiccontext "github.com/pengelbrecht/ticks/internal/context"
	"github.com/pengelbrecht/ticks/internal/github"
	"github.com/pengelbrecht/ticks/internal/tick"
)

var contextCmd = &cobra.Command{
	Use:   "context <epic-id>",
	Short: "View the generated context document for an epic",
	Long: `View the generated context document for an epic.

Context documents are generated by tk run when running an epic for the first time.
They contain information about relevant code, architecture notes, and conventions
that help the AI agent understand the codebase when working on tasks.

Context documents are stored in .tick/logs/context/<epic-id>.md`,
	Args: cobra.ExactArgs(1),
	RunE: runContext,
}

var contextShowPath bool

func init() {
	contextCmd.Flags().BoolVar(&contextShowPath, "path", false, "output the file path instead of content")
	rootCmd.AddCommand(contextCmd)
}

func runContext(cmd *cobra.Command, args []string) error {
	root, err := repoRoot()
	if err != nil {
		return fmt.Errorf("failed to detect repo root: %w", err)
	}

	project, err := github.DetectProject(nil)
	if err != nil {
		return fmt.Errorf("failed to detect project: %w", err)
	}

	epicID, err := github.NormalizeID(project, args[0])
	if err != nil {
		return fmt.Errorf("invalid id: %w", err)
	}

	// Verify the epic exists
	store := tick.NewStore(filepath.Join(root, ".tick"))
	t, err := store.Read(epicID)
	if err != nil {
		return fmt.Errorf("failed to read tick: %w", err)
	}
	if t.Type != "epic" {
		return fmt.Errorf("%s is a %s, not an epic", epicID, t.Type)
	}

	// Create context store and compute file path
	contextStore := epiccontext.NewStore()
	filePath := filepath.Join(root, contextStore.Dir(), epicID+".md")

	if contextShowPath {
		fmt.Println(filePath)
		return nil
	}

	// Load the context document
	content, err := contextStore.Load(epicID)
	if err != nil {
		return fmt.Errorf("failed to read context: %w", err)
	}

	if content == "" {
		return fmt.Errorf("no context document found for epic %s\n\nContext is generated when you first run 'tk run %s'", epicID, epicID)
	}

	// Output the content
	fmt.Print(content)
	if content[len(content)-1] != '\n' {
		fmt.Println()
	}

	return nil
}
